### ISSUE TITLE
how to fix the build error?

### ISSUE THREAD

**Issue by luckypoem** [cdupont/CorentinDupont-WebPage#4]
hi

root@AR:/usr/local/CorentinDupont-WebPage# .stack-work/dist/i386-linux/Cabal-1.22.4.0/build/site/site build

it exports:
...
 updated blog/posts/Cosmology/2014-01-16-Aliens.md
  updated blog/posts/Cosmology/2014-04-07-Religion-Self.md
  updated blog/posts/Cosmology/2014-07-21-Math-Structure.md
  updated blog/posts/Cosmology/2014-08-30-Time.md
  updated blog/posts/Cosmology/2015-01-28-Dimensions.md
  updated blog/posts/Cosmology/2015-02-02-Comprehensible.md
  updated blog/posts/Cosmology/2015-03-10-Mattress.md
  updated blog/posts/Cosmology/2015-05-01-LightSpeed.md
  updated blog/posts/Cosmology/2015-05-18-Life3D.md
  updated blog/posts/Cosmology/2015-09-03-Einstein.md
  updated blog/posts/Math/2013-12-15-Intro-to-Godel-Theorem.md
  [ERROR] R: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
root@AR:/usr/local/CorentinDupont-WebPage#

how to fix the build error?
thank u a lot.

**Comment by cdupont** [comment]
Sorry didn't see your comment. Does it work now?

**Comment by luckypoem** [comment]
No.so how to fix it?

**Comment by cdupont** [comment]
Actually it's pending this fix: https://github.com/diagrams/diagrams-pandoc/issues/11

**Comment by luckypoem** [comment]
hi.

i modified stack.yaml:
root@AR:/usr/local/CorentinDupont-WebPage# cat stack.yaml
flags: {}
packages:
- '.'
  #- ../Haskell/R-pandoc
#- ../Haskell/diagrams-pandoc
  #- ../Haskell/diagrams-builder
extra-deps:
- Cabal-1.24.2.0
- HTTP-4000.2.23
- aeson-0.9.0.1
- cmark-0.4.1
- diagrams-pandoc-0.2
- pandoc-1.15.2.1
- pandoc-citeproc-0.8.1.3
- pandoc-types-1.12.4.7
- R-pandoc-0.2.2
- diagrams-builder-0.7.2.4
- hakyll-4.8.3.2
resolver: lts-6.11
root@AR:/usr/local/CorentinDupont-WebPage# stack build
it shows:
...
--  While building package R-pandoc-0.2.2 using:
      /root/.stack/setup-exe-cache/i386-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/i386-linux/Cabal-1.22.5.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /usr/local/CorentinDupont-WebPage/.stack-work/logs/R-pandoc-0.2.2.log

    Configuring R-pandoc-0.2.2...
    Building R-pandoc-0.2.2...
    Preprocessing library R-pandoc-0.2.2...
    [1 of 1] Compiling Text.Pandoc.R    ( src/Text/Pandoc/R.hs, .stack-work/dist/i386-linux/Cabal-1.22.5.0/build/Text/Pandoc/R.o )
    
    /tmp/stack2461/R-pandoc-0.2.2/src/Text/Pandoc/R.hs:57:20:
        Couldn't match expected type ‘(FilePath, [Char]) -> Inline’
                    with actual type ‘Inline’
        The function ‘Image’ is applied to three arguments,
        but its type ‘[Inline] -> Target -> Inline’ has only two
        In the expression: Image nullAttr [] (file, "")
        In an equation for ‘insertImage’:
            insertImage file = Image nullAttr [] (file, "")
    
    /tmp/stack2461/R-pandoc-0.2.2/src/Text/Pandoc/R.hs:57:26:
        Couldn't match type ‘(String, [String], [(String, String)])’
                       with ‘[Inline]’
        Expected type: [Inline]
          Actual type: Attr
        In the first argument of ‘Image’, namely ‘nullAttr’
        In the expression: Image nullAttr [] (file, "")
    
    /tmp/stack2461/R-pandoc-0.2.2/src/Text/Pandoc/R.hs:57:35:
        Couldn't match type ‘[t0]’ with ‘(String, String)’
        Expected type: Target
          Actual type: [t0]
        In the second argument of ‘Image’, namely ‘[]’
        In the expression: Image nullAttr [] (file, "")
        In an equation for ‘insertImage’:
            insertImage file = Image nullAttr [] (file, "")
root@AR:/usr/local/CorentinDupont-WebPage#

installing R-pandoc failed.so how to install R-pandoc successfully?

**Comment by luckypoem** [comment]
any idea on how to fix the error?

**Comment by cdupont** [comment]
I'm working on it, should be ready tonight.

**Comment by cdupont** [comment]
It should be building now.
Although diagrams-pandoc does not works, it is quite broken at the moment

**Comment by luckypoem** [comment]
now it's ok.tks
